### ISSUE TITLE
Sequencer: handle the case where blocks go backwards

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/op-espresso-integration#37]
There is a limitation in our current hacky implementation of L1 blocks in HotShot block headers, where the leader doesn't know about the previous L1 block, and thus, if their ETH client is lagging for any reason, may propose an L1 block that is actually before the parent's L1 block. This breaks a fundamental assumption of the OP node. So we need to add a rule that says if the L1 origin has gone backwards, the sequencer can just use the L2 parent's L1 origin, and otherwise carry on as normal.

I also need to think more about what happens if a HotShot block's _timestamp_ goes backwards.

**Comment by jbearer** [comment]
I think HotShot timestamps decreasing occasionally is OK for demo purposes.

The way the query service endpoint is currently written (https://github.com/EspressoSystems/espresso-sequencer/pull/555), it will always return the first block sequenced with timestamp at least equal to the start of the requested window. This is the same behavior we would have if the timestamps were always increasing. Furthermore, since `prev` is by definition sequenced before the first block in the window, it will always have timestamp less than the first block in the window, which is a supposed invariant of the relationship between `prev` and the first block.

For the end of the window, the query service takes the first block after the start of the window whose timestamp is at least `end`. This becomes `next` and the block before it becomes the last block in the window. Since `next` is by definition the first block in sequence order with timestamp at least than `end`, `next` has timestamp less than `end`, and thus the two blocks that define the end of the window also have decreasing timestamps.

The OP node only really cares about those four blocks: two defining the start of the window and two defining the end. It assumes that the blocks in the window have timestamps between the start and end, but we don't actually check this, and nothing breaks if it is violated. Technically the sequencer does check the timestamps of the middle blocks, but only to sanity check the data returned by the query service, so we can just turn those checks from errors into warning logs.

**Comment by nomaxg** [comment]
> I think HotShot timestamps decreasing occasionally is OK for demo purposes.
> 
> The way the query service endpoint is currently written ([EspressoSystems/espresso-sequencer#555](https://github.com/EspressoSystems/espresso-sequencer/pull/555)), it will always return the first block sequenced with timestamp at least equal to the start of the requested window. This is the same behavior we would have if the timestamps were always increasing. Furthermore, since `prev` is by definition sequenced before the first block in the window, it will always have timestamp less than the first block in the window, which is a supposed invariant of the relationship between `prev` and the first block.
> 
> For the end of the window, the query service takes the first block after the start of the window whose timestamp is at least `end`. This becomes `next` and the block before it becomes the last block in the window. Since `next` is by definition the first block in sequence order with timestamp at least than `end`, `next` has timestamp less than `end`, and thus the two blocks that define the end of the window also have decreasing timestamps.
> 
> The OP node only really cares about those four blocks: two defining the start of the window and two defining the end. It assumes that the blocks in the window have timestamps between the start and end, but we don't actually check this, and nothing breaks if it is violated. Technically the sequencer does check the timestamps of the middle blocks, but only to sanity check the data returned by the query service, so we can just turn those checks from errors into warning logs.

This seems sound to me, the bounds should be correct since we are always returning the first block sequenced that has a certain spot relative to the window
