### ISSUE TITLE
Better definition of L1Origin

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/op-espresso-integration#53]
Currently, we try to use the `l1_head` of the first HotShot block in an OP batch as the L1 origin for that batch, and adjust if needed. This has problems, namely
* This L1 block can be more recent than the start of the L2 window, since the corresponding HotShot block came from after the start of the window (#52)
* This L1 block can be old, since we do not create the L2 batch until reaching the _end_ of the window, leading to higher latency for deposits and increasing the likelihood of hitting the "L1 origin too old" edge case, which necessitates an empty batch

The only properties we really want from the L1 origin are
1. It is a block in the past, so the OP nodes don't have to block waiting for it to be produced
2. It is relatively recent, to satisfy the OP constraints
3. It is deterministic based on the HotShot block stream

We don't actually care that it is directly associated with any specific HotShot block in the window. Thus, I propose a better way of determining the L1 origin: use the `l1_head` of the first HotShot block _after_ the L2 batch window (`NextBatchFirstBlock`). Adjust if needed. Produce an empty batch iff the _adjusted_ L1 origin requires it.

This L1 head is the most recent one we can get from HotShot without waiting any longer than necessary (since we need to wait for `NextBatchFirstBlock` to build `Justification` anyways), which gives better latency for deposits on average and decreases the risk of hitting the "L1 origin too old" edge case and producing needless empty blocks. OTOH it is more likely that this L1 origin will be "too new", having skipped an L1 block since the previous L1 origin, but this is fine: we just use the previous L1 origin + 1 in this case, which is as recent of an L1 block as the OP stack will allow. This also smoothly handles the case where the L1 block is newer than the L2 batch -- in fact, with this method, it often will be, but that is taken care of by the "adjust if needed" step.

The flow of "choose an L1, adjust if needed according to deterministic rules, and then force the batch to be empty only if the adjusted origin requires it" is 
* simpler to understand than our current approach, which is almost the opposite: choose an L1, force the batch to be empty if it is invalid, and adjust accordingly
* easier to abstract so that the sequencer and derivation pipeline can share code. For example, we can have a `ChooseL1Origin(cfg, prev L2BlockRef, suggestByHotShot L1BlockRef)` function that the sequencer uses to pick the L1 origin and the batch queue uses to compare against. Then we can have a `BatchMustBeEmpty(cfg, prev L2BlockRef, l1Origin L1BlockRef)` that both the sequencer and the batch queue use to decide if the batch should be empty. This functional approach (as opposed to a more constraint-based approach) is also nicely in line with the idea of L2 batches being deterministically derived form HotShot blocks.
* less likely to produce needless empty batches, since we allow a batch to be full if deterministically adjusting the L1 origin brings us within the OP constraints

This will take care of both #52 (which we need to fix, because I believe we will hit it if we run a testnet for long enough) and #40 (which will increase average throughput and improve UX).

The only downside, I think, is that the sequencer can't detect edge cases after seeing the first block of the window and build empty blocks immediately; it has to wait for the end of the window. I think this is fine, since these cases are rare by design and anyways, there's nothing wrong with producing batches at a regular cadence and nothing really gained by rushing to produce empty batches.

**Comment by nomaxg** [comment]
I like this approach a lot, the constraints implementation looks a lot simpler. Since the edge cases involving empty batches are rare, it is probably fine that the sequencer has to wait.
